SportsStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository repo) //также для Ninject
        {
            repository = repo;
        }

        public ViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return View(categories);
        }

    }
}

SportsStore.WebUI/Controllers/UserController.cs
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class UserController : Controller
    {
        private IUserRepository repository;

		public const string LogonSuccess = "LogOn success!";
		public const string PasswordIncorrect = "Typed password is incorrect!";
		public const string LoginAndPassIncorrect = "Typed login and password are incorrect!";

		public UserController(IUserRepository repo)
		{
			repository = repo;
		}

		public ViewResult UserPanel(string returnUrl)
		{
			return View(GetUserVM());
		}

		public ViewResult CheckAndResult(LogOnVM inputVM, string returnUrl)
		{
			UserViewModel sessionUserVM = GetUserVM();
			sessionUserVM.ReturnUrl = returnUrl;
			sessionUserVM.IsLogOn = false;
			User user = repository.Users
				.FirstOrDefault(u => u.Login == inputVM.Login);
			if (user != null)
			{
				if (user.Password == inputVM.Password)
				{
					sessionUserVM.IsLogOn = true;
					sessionUserVM.User = new Domain.Entities.User(user);
					sessionUserVM.LogonResult = LogonSuccess;
					SetUserVM(sessionUserVM);
				}
				else
				{
					sessionUserVM.LogonResult = PasswordIncorrect;
				}
			}
			else
			{
				sessionUserVM.LogonResult = LoginAndPassIncorrect;
			}
			return View(sessionUserVM);
		}

		private UserViewModel GetUserVM()
		{
			UserViewModel userVM = null;
			try{ userVM = (UserViewModel)Session["UserVM"]; } catch { };
			if (userVM == null)
			{
				User user = new Domain.Entities.User();
				user.Login = "Guest";
				userVM = new UserViewModel(user);
				Session["UserVM"] = userVM;
			}
			return userVM;
		}
		private void SetUserVM(UserViewModel userVM)
		{
			Session["UserVM"] = userVM;
		}

		public ViewResult LogOn()
		{
			return View();
		}

		public ActionResult LogOff()
		{
			UserViewModel uVM = GetUserVM();
			uVM.IsLogOn = false;
			SetUserVM(uVM);
			return RedirectToAction("List", "Product");			
		}

		public ViewResult Register()
		{
			return View();
		}


		public ViewResult ToPrivateOffice()
		{
			return View();
		}

        public ActionResult Index()
        {
            return View();
        }

    }
}

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="item"> 
    <h3>@Model.Name</h3> 
    @Model.Description 
 
    @using(Html.BeginForm("AddToCart", "Cart")) { 
        @Html.HiddenFor(x => x.ProductID) 
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery) 
        <input type="submit" value="Add to cart" /> 
    } 
 
    <h4>@Model.Price.ToString("c")</h4> 
</div> 

SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
</head>
<body>
    <div id="header">
        <div class="title">
			SPORTS STORE 
        </div> 
		@{Html.RenderAction("UserPanel", "User");}
	</div>
	
    <div id="categories">
        @{Html.RenderAction("Menu", "Nav"); }
    </div>
    <div id="content">
        @RenderBody()
    </div>
</body>
</html>